INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (1, '태어날 때부터 등에 큰 종자를 역사하고 있다. 큰 나뭇잎을 머리 위로 둥글게 내밀어 빛을 받으며 자라난다.', '이상해씨', 1, 800, 'GRASS');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (2, '큰 잎사귀를 휘젓고 주변의 냄새를 맡아 식물이나 날씨의 변화를 감지한다. 호기심 많은 성격이다.', '이상해풀', 2, 1000, 'GRASS');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (3, '큰 꽃잎으로 빛을 받으면 꽃이 피어나서 아름다운 빛을 내뿜는다. 화창한 날씨를 좋아한다.', '이상해꽃', 3, 1200, 'GRASS');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (4, '등껍질에 물을 담아서 무게를 늘리면 바다에서 헤엄쳐 갈 수 있다. 조용한 성격을 가졌다.', '꼬부기', 4, 800, 'WATER');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (5, '날카로운 발톱을 가진 포켓몬으로 화가 날 때 불꽃을 내뿜는다. 날씨가 더울수록 활동적으로 움직인다.', '파이리', 7, 800, 'FIRE');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (6, '작고 부드러운 몸을 가졌다. 잎사귀나 나뭇껍질을 먹으며 자라나서 진화한다.', '캐터피', 10, 150, 'BUG');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (7, '무엇이든 전기 주입을 시도하며 주위를 봉인한다. 번개구름이 있을 때 활기를 얻는다.', '피카츄', 25, 1000, 'ELECTRIC');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (8, '위험한 독가스를 내뿜어 상대를 혼란시키고 공격한다. 악취를 뿜어 환경을 오염시킨다.', '또도가스', 110, 750, 'POISON');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (9, '어릴 때부터 목소리 연습을 해서 다양한 목소리로 소리를 내는 것을 즐긴다.', '피죤투', 36, 800, 'NORMAL');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (10, '작고 귀여운 몸을 가졌다. 달콤한 노래로 상대를 화나게 하지 않도록 한다.', '푸린', 39, 350, 'NORMAL');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (11, '무거운 머리를 내리누르고 있으면 고개가 물에 빠지고 말고가 된다. 천천히 움직인다.', '야돈', 57, 600, 'PSYCHIC');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (12, '다양한 상황에서 환경에 맞게 진화할 수 있는 능력을 가졌다. 친근한 성격을 가지고 있다.', '이브이', 133, 1200, 'NORMAL');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (13, '동상을 보는 동안 상대방의 표정이나 동작을 따라한다. 꼼꼼한 성격을 가지고 있다.', '잠만보', 143, 300, 'NORMAL');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (14, '신비한 능력을 가지고 있는 포켓몬이다. 텔레파시를 사용하여 사물을 움직인다고 전해진다.', '뮤', 151, 5000, 'PSYCHIC');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (15, '바위와 땅 속에서 서식하는 대형 포켓몬으로, 긴 몸과 딱딱한 돌 같은 피부를 가지고 있다.', '롱스톤', 95, 2000, 'ROCK');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (16, '사람이나 포켓몬을 등에 태워 바다를 건너는 것을 매우 좋아한다. 사람의 말을 이해할 수 있다.', '라프라스', 131, 2000, 'ICE');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (17, '데구리를 수없이 들었다 놨다 하며 전신의 근육을 단련한다. 모든 격투기를 사용한다.', '알통몬', 66, 500, 'FIGHTING');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (18, '넓은 영역을 날아다니며 먹이를 찾는다. 발달한 발톱으로 먹이를 꼼짝 못 하게 한다.', '피죤', 17, 300, 'FLYING');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (19, '가스로 된 몸으로 휘감은 다음 먹이의 피부를 통해 조금씩 독을 흘려보내어 약하게 만든다.', '고오스', 92, 1300, 'GHOST');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (20, '드넓은 바다 어딘가에는 망나뇽만이 모여 사는 섬이 있다고 한다.', '망나뇽', 149, 3000, 'DRAGON');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (21, '달의 파동을 몸에 쬐면 고리 모양이 희미하게 빛나며 이상한 힘에 눈을 뜬다.', '블래키', 197, 1800, 'DARK');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (22, '머리의 털이 단단해져서 철로 된 헬멧처럼 되었다. 매우 호전적인 성질을 가졌다.', '나이킹', 863, 1500, 'STEEL');
INSERT INTO t_pokemon (id, description, name, number, price, type) VALUES (28, '귀여운 표정과 동작으로 인기가 많다. 조용한 산속에서 동료들과 사는 것으로 여겨지고 있다.', '삐삐', 333, 2300, 'FAIRY');
