INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (1, '일반적인 포켓몬을 잡을 수 있는 볼.', '몬스터볼', 1, 200, '볼');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (2, '더 강력한 포켓몬을 잡을 수 있는 볼.', '슈퍼볼', 2, 500, '볼');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (3, '매우 강력한 포켓몬을 잡을 수 있는 볼.', '하이퍼볼', 3, 800, '볼');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (4, '포켓몬을 확실하게 잡을 수 있는 최고급 볼. 럭셔리한 디자인이 특징이다.', '프리미어볼', 4, 1500, '볼');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (5, '포켓몬을 확실하게 잡을 수 있는 최고급 볼.', '마스터볼', 5, 1000, '볼');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (6, '포켓몬을 잡을 확률을 크게 높여주는 열매.', '황금 라즈열매', 6, 500, '볼');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (7, '포켓몬 알을 빠르게 부화시켜주는 장치. 제한 없이 사용 가능하다.', '무한 부화장치', 7, 800, '부화장치');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (8, '포켓몬 알을 부화시켜주는 장치.', '부화장치', 8, 400, '부화장치');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (9, '포켓몬 알을 빠르게 부화시켜주는 장치. 좀 더 강력하게 작동한다.', '슈퍼 부화장치', 9, 1200, '부화장치');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (10, '포켓몬의 체력을 다소 회복시켜주는 열매.', '나나열매', 10, 200, '열매');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (11, '포켓몬을 잡을 확률을 약간 높여주는 열매.', '라즈열매', 11, 300, '열매');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (12, '포켓몬의 체력을 다소 회복시켜주는 열매.', '은 파인열매', 12, 250, '열매');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (13, '포켓몬의 체력을 약간 회복시켜주는 열매.', '파인열매', 13, 150, '열매');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (14, '체력을 즉시 회복시켜주는 약. 약간의 상처에 좋다.', '고급상처약', 14, 300, '회복');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (15, '체력을 즉시 회복시켜주는 약.', '상처약', 15, 100, '회복');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (16, '체력을 즉시 회복시켜주는 약. 더 좋은 효과를 제공한다.', '좋은상처약', 16, 500, '회복');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (17, '체력과 기력을 모두 완전히 회복시켜주는 강력한 약.', '풀회복약', 17, 800, '회복');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (18, '전투 도중 기력을 조금 회복시켜주는 아이템.', '기력의덩어리', 18, 150, '회복');
INSERT INTO db_gochowoo.t_item (id, description, name, number, price, type) VALUES (19, '전투 도중 기력을 약간 회복시켜주는 작은 조각.', '기력의조각', 19, 50, '회복');
